name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['bug', 'fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor', 'deps']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No user-facing changes in this release.'

