apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://four-brain-prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}

  - name: loki
    type: loki
    access: proxy
    url: http://four-brain-loki:3100
    isDefault: false
    editable: true
    uid: loki
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData: {}
